### ISSUE TITLE
Update the BOM Recipe to Accommodate the Latest Archetype

### ISSUE THREAD

**Issue by gounthar** [jenkins-infra/plugin-modernizer-tool#122]
## Current Situation
We [are currently using](https://github.com/jenkinsci/plugin-modernizer-tool/blob/main/plugin-modernizer-core/src/main/resources/recipe_data.yaml#L7C10-L7C47) the existing [OpenRewrite BOM recipe](https://docs.openrewrite.org/recipes/jenkins/addpluginsbom) for our plugin modernization efforts.

## Question
Does this recipe cover the case of the latest [Jenkins archetype](https://github.com/jenkinsci/archetypes/pull/737/files)?

## Potential Actions

If the current recipe covers the latest archetype:
- No action required.

If the current recipe does not cover the latest archetype:

1. Create a meta-recipe that:
   - Adds the `jenkins.baseline` property
   - Uses this property to reference the BOM

2. Modify the existing recipe by:
   - Creating a PR on the [OpenRewrite repository](https://github.com/openrewrite/rewrite-jenkins/blob/main/src/main/java/org/openrewrite/jenkins/AddPluginsBom.java)

## Precedent
The OpenRewrite team has been receptive to contributions in the past. They [accepted our contribution](https://github.com/openrewrite/rewrite-jenkins/issues/52) when the archetype for the Jenkinsfile changed months ago.

## Next Steps
1. Verify if the current recipe covers the latest archetype.
2. If not, decide between creating a meta-recipe or modifying the existing one.
3. If modifying the existing recipe, prepare a PR for the OpenRewrite repository.

Your thoughts and feedback on this approach are welcome.

**Comment by jonesbusy** [comment]
From what I understand is the declarative recipe https://github.com/openrewrite/rewrite-jenkins/commit/30e736b0063026b0ed504a0b813d4f4c859d67e7 that define the minimum version

The "real" version is fetch here : https://github.com/openrewrite/rewrite-jenkins/blob/main/src/main/java/org/openrewrite/jenkins/Jenkins.java#L43

Basially it doesn't check the property by itself but the managed version of org.jenkins-ci.main:jenkins-core artifact (that is influenced by the `jenkins.version` property

**Comment by jonesbusy** [comment]
Downstream PR https://github.com/openrewrite/rewrite/pull/4404

**Comment by jonesbusy** [comment]
Other PR related to new archetype https://github.com/openrewrite/rewrite-jenkins/pull/73 will not

**Comment by jonesbusy** [comment]
Partially fixed by #512 but missing some Improvement for comment and order of property

**Comment by jonesbusy** [comment]
Fixed on latest release 1046.v7cedb_6c8df3f

Some example : https://github.com/jenkinsci/metrics-plugin/pull/296/files
