### ISSUE TITLE
Distribute the CLI via HomeBrew

### ISSUE THREAD

**Issue by jonesbusy** [jenkins-infra/plugin-modernizer-tool#239]
### What feature do you want to see added?

Create CLI distribution via Homebrew to support OSX and Linux host

Example https://github.com/jenkins-infra/homebrew-tap

**Comment by dduportal** [comment]
Following <>:

On my M2 MacBook Air:

```
$ brew tap jenkins-infra/homebrew-tap      
==> Tapping jenkins-infra/tap
Cloning into '/opt/homebrew/Library/Taps/jenkins-infra/homebrew-tap'...
remote: Enumerating objects: 154, done.
remote: Counting objects: 100% (154/154), done.
remote: Compressing objects: 100% (148/148), done.
remote: Total 154 (delta 44), reused 8 (delta 3), pack-reused 0 (from 0)
Receiving objects: 100% (154/154), 25.44 KiB | 1.59 MiB/s, done.
Resolving deltas: 100% (44/44), done.
Tapped 5 formulae (18 files, 43.6KB).

$ brew install plugin-modernizer
==> Fetching jenkins-infra/tap/plugin-modernizer
==> Downloading https://github.com/jenkins-infra/plugin-modernizer-tool/releases/download/911.v211a_1d5a_7a_a_f/jenkins-plugin-modernizer-911.v211a_1d5a_7a_a_f.jar
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/795839419/dda27885-cb86-4dee-9651-cfe7d0298cb6?X-Amz-Algorithm=AWS4-HMAC-
#################################################################################################################################################################### 100.0%
==> Installing plugin-modernizer from jenkins-infra/tap
🍺  /opt/homebrew/Cellar/plugin-modernizer/911: 5 files, 180.2MB, built in 1 second
==> Running `brew cleanup plugin-modernizer`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).

$ plugin-modernizer --version
plugin modernizer 911.v211a_1d5a_7a_a_f (2024-12-10T11:48:50Z)
```

👏

**Comment by jonesbusy** [comment]
Update via workflow is also a success https://github.com/jenkins-infra/homebrew-tap/commit/e7e729be70eacaf8a1d6acd28dfa18ef8eb70d83

https://github.com/jenkins-infra/plugin-modernizer-tool/actions/runs/12260378275/job/34204844908

![success](https://github.com/user-attachments/assets/beccfdd4-c31d-4868-b727-5955a9592e14)

There are some minor things to tweak (like the git username/email) or avoid creating tags on the repo

I will keep this issue open until and fix them tomorrow

**Comment by jonesbusy** [comment]
This was not an easy task. Lots of try and retry.

But https://github.com/jenkins-infra/plugin-modernizer-tool/releases/tag/933.vb_2713b_667f16 is the first release fully delivery by  cd until homebrew distribution

Closing this issue

**Comment by gounthar** [comment]
Thank you for your patience and dedication in leading this to success!
