### ISSUE TITLE
Proposal: Enable Modernization of Plugins in Private Repositories

### ISSUE THREAD

**Issue by gounthar** [jenkins-infra/plugin-modernizer-tool#318]
## Current Situation

Currently, our modernization process relies solely on the update center to retrieve plugin repositories for modernization efforts.

## Challenge

This approach limits our ability to modernize certain types of plugins:

1. Plugins with security issues that have been forked into private repositories for resolution
2. Plugins developed by private companies that are not (yet) part of the jenkinsci organization
3. Proprietary plugins that will remain outside the jenkinsci organization

## Proposed Solution

We propose expanding the modernization capabilities to include plugins in private repositories. This could be achieved by:

1. Allowing the use of repository URLs as input for the modernization process
2. Implementing a mechanism to authenticate and access private repositories using appropriate environment variables

## Implementation Considerations

To implement this feature, we would need to:

1. Modify the input process to accept repository URLs in addition to plugin names
2. Develop a secure method for handling authentication credentials (e.g., using environment variables)
3. Ensure the tool can clone, fork, and create pull requests for private repositories
4. Update documentation to reflect these new capabilities and explain the setup process

## Benefits

This enhancement would:

1. Increase the tool's flexibility and usefulness
2. Enable faster resolution of security issues in plugins
3. Support companies with proprietary plugins in keeping their extensions up-to-date

## Questions for Discussion

1. What security measures should we implement to protect authentication credentials?
2. How can we ensure the tool remains easy to use while adding this functionality?
3. Are there any potential drawbacks or risks associated with this approach?

We welcome your thoughts and feedback on this proposal to help shape the future development of our plugin modernization tool.

**Comment by jonesbusy** [comment]
In theory it should be possible. Also since https://github.com/jenkins-infra/plugin-modernizer-tool/pull/458 we can add a custom API URL (for example if your org is using self hosted GitHub enterprise)

Different URL can be overriden by env vars or CLI args

JENKINS_UC
JENKINS_PLUGIN_INFO
JENKINS_PHS
JENKINS_PLUGINS_STATS_INSTALLATIONS_URL
GH_TARGET_ORGANISATION

I think this issue just deserve documentation and one validation 

I will most likely need to finish https://github.com/jenkins-infra/plugin-modernizer-tool/issues/420 to split global option and command option

**Comment by jonesbusy** [comment]
Also now support local plugin via #503.

Integration test with testcontainer show that is possible to override all options yo.make it work with private plugin as long they are published on GitHub or GitHub enterprise
