### ISSUE TITLE
Missing XML Declaration in Jelly Files - <?jelly escape-by-default='true'?>

### ISSUE THREAD

**Issue by gounthar** [jenkins-infra/plugin-modernizer-tool#349]
### What feature do you want to see added?

While working on the [AnchorChain plugin](https://github.com/jenkinsci/anchor-chain-plugin), I discovered that several Jelly files were missing the required XML declaration:
```<?jelly escape-by-default='true'?>```

According to the [Jenkins documentation](https://www.jenkins.io/doc/developer/tutorial-improve/move-description-to-index/#move-description-to-srcmainresourcesindex-jelly), when migrating the `<description>` tag from `pom.xml` to a Jelly file, this declaration is mandatory.

While there is [an existing OpenRewrite recipe](https://docs.openrewrite.org/recipes/jenkins/createindexjelly) that handles the file creation, it doesn't address cases where the file exists but lacks the required declaration.

Questions for Discussion:

1. Which existing PluginModernizer recipe would be most appropriate to incorporate the `org.openrewrite.jenkins.CreateIndexJelly` recipe?

2. What would be the best approach to implement the missing declaration fix:
  - Modify the existing OpenRewrite recipe
  - Create a new dedicated recipe
  - Use a simpler approach similar to our [Dependabot solution](https://github.com/jenkinsci/plugin-modernizer-tool/pull/338) or https://docs.openrewrite.org/recipes/text/appendtotextfile (though this may be insufficient)

Your guidance on these implementation approaches would be appreciated.

### Are you interested in contributing this feature?

Yes. In the meantime, I will give a try at [org.openrewrite.xml.XsltTransformation](https://docs.openrewrite.org/recipes/xml/xslttransformation).

**Comment by gounthar** [comment]
I discussed the matter there too: https://rewriteoss.slack.com/archives/C01A843MWG5/p1729698356197269 .

**Comment by jonesbusy** [comment]
Perhaps plain text parsing is probably the easiest. At the end we just need to modify one line of the document ?
