### ISSUE TITLE
Pull Requests: Only List Recipes with Repository Impact

### ISSUE THREAD

**Issue by gounthar** [jenkins-infra/plugin-modernizer-tool#370]
### What feature do you want to see added?

Currently, our process involves listing all applied recipes in the pull request title, regardless of whether they resulted in changes to the repository.

For example, [this PR](https://github.com/jenkinsci/configurationslicing-plugin/pull/295) was renamed by a maintainer because the original title was misleading compared to the actual (minor) changes.

To improve clarity, we should:

1. Only include recipe names in the pull request title if they resulted in changes to the repository.
2. Consider adding a new section in the pull request body to list recipes that did not have an effect, if desired.

This approach will ensure the pull request titles accurately reflect the substantive changes being introduced, making it easier for reviewers to understand the impact.

**Comment by jonesbusy** [comment]
Not relevant since https://github.com/jenkins-infra/plugin-modernizer-tool/pull/419
