### ISSUE TITLE
Restore PR template

### ISSUE THREAD

**Issue by jonesbusy** [jenkins-infra/plugin-modernizer-tool#386]
### Reproduction steps

Since we move from jenkinsci to jenkins-infra we lost the PR template (set on org level)

Let's add a https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository into this repos

### Expected Results

A PR template

### Actual Results

No PR template

**Comment by SohamJuneja** [comment]
I've submitted a PR , please review and suggest if any changes required
