### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by jonesbusy** [jenkins-infra/plugin-modernizer-tool#448]
### What feature do you want to see added?

Right now we rely exclusively on unit test

We should have some integration test to test the CLI after packaging

This could be achieved using failsafe plugin and maven invoker and running integration test after assembly file

A first iteration could be to run the jar with only some command in dry-run mode

This would allow to catch classpath or packaging issue which can be detected with unit tests

**Comment by jonesbusy** [comment]
One example when a unit test is passing when fail at execution

![example](https://github.com/user-attachments/assets/2c8a6f56-6c10-4095-ab03-48b4df07f84b)

**Comment by SohamJuneja** [comment]
Plan to add integration tests for the CLI using the Maven Failsafe and Invoker plugins. The tests will run in a dry-run mode after packaging (via assembly) to catch classpath and packaging issues not covered by unit tests. I'll update the pom.xml, add integration test cases under src/it, and ensure they execute correctly after the assembly step. Let me know if this approach works or if there are any suggestions!

**Comment by jonesbusy** [comment]
Sure looks good thanks! There are other component that miss tests, like Maven Invoker. 

Any PR that increase coverage is good

**Comment by SohamJuneja** [comment]
Submitted a PR , please review as I am a beginner and this is one of my first contributions this side

**Comment by SohamJuneja** [comment]
Working on the required changes , will submit a fresh PR. Thanks for the feedback
