### ISSUE TITLE
Support for signed commits

### ISSUE THREAD

**Issue by jonesbusy** [jenkins-infra/plugin-modernizer-tool#460]
### What feature do you want to see added?

SInce JGit version 7.1 it support SSH keys signing. 

Perhaps it could be the easiest solution rather than using GPG signing

To investigate

**Comment by jonesbusy** [comment]
Will be probably one of my next task.

Some plugin require signed commits : https://github.com/jenkinsci/token-macro-plugin/pull/239

**Comment by gounthar** [comment]
Would it be possible to include instructions in the documentation on how users can configure their SSH key for this tool?
