### ISSUE TITLE
Recipe - Remove release draft config if a plugin uses cd workflow

### ISSUE THREAD

**Issue by jonesbusy** [jenkins-infra/plugin-modernizer-tool#523]
### What feature do you want to see added?

Release drafter config must be removed when a plugin declarare a cd workflow

Tests are needed. Get inspired from `shouldNotAddDependabotIfRenovateConfigured` which is similar (add dependabot only if renovate is NOT configured, to avoid

### Upstream changes

None. Justification: I saw many plugin using cd but forgot to remove release drafter config

**Comment by Yash-jaiswal2509** [comment]
Hi, can i work on this issue?

**Comment by jonesbusy** [comment]
Fixed already by #528

**Comment by jonesbusy** [comment]
#459 or #460 I'm not planning to work on this in the following weeks. If you are interested to get familiar with the codebase

**Comment by Yash-jaiswal2509** [comment]
Sure, i will try. 
Thank you

**Comment by jonesbusy** [comment]
Or #517 for OpenRewrite Recipes is an option

**Comment by Yash-jaiswal2509** [comment]
Okay
