### ISSUE TITLE
Create One PR per Set of Applied Recipes

### ISSUE THREAD

**Issue by gounthar** [jenkins-infra/plugin-modernizer-tool#93]
## Current Situation
Currently, we create a single pull request (PR) regardless of the number or type of recipes specified on the command line.

## Proposed Improvement
We should consider creating separate PRs for each set of applied recipes. This approach would involve:

1. Generating a unique checksum for each set of recipes
2. Using this checksum to name a new branch
3. Creating a specific branch with that name for each set of recipes

## Benefits
1. **Targeted Reviews**: This approach allows maintainers to review changes that focus on specific aspects of the code.
2. **Manageable PRs**: By avoiding large PRs with numerous changes, we increase the likelihood of maintainers reviewing the proposed modifications.
3. **Improved Organization**: Separate branches and PRs for each set of recipes provide better organization and traceability of changes.

## Implementation Idea
Create one branch and corresponding PR per set of recipes. This strategy ensures that the resulting PRs are:
- Focused on specific changes
- Easier for maintainers to review
- More likely to be considered and merged

## Conclusion
By implementing this approach, we can enhance the effectiveness of our modernization process and improve collaboration with project maintainers. This method aligns with best practices in code review and project management, potentially leading to faster adoption of necessary updates.

**Comment by jonesbusy** [comment]
I think we should simplify and allow only one recipe to run per execution. If we need to run more recipes, we should create composite/yaml recipes.

I will simplify a lot of things (for example allow more user friendly PR title)

**Comment by jonesbusy** [comment]
Closed. Only one recipe can be run at a time
